---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7
  - name: chef/ubuntu-14.04

suites:
  - name: default
    run_list:

      - recipe[arcgis::all_installed]

    attributes:
